### ISSUE TITLE
Error on Sync

### ISSUE THREAD

**Issue by CodeDruid13** [subsub/lottiebottomnavbar#1]
Am getting Failed to resolve: com.subkhansarif error yet everything has been set in order.

**Comment by subsub** [comment]
Can I see your project level gradle and app module gradle?

**Comment by CodeDruid13** [comment]
`app module gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "codedruid13.marcos.com"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v13:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.subkhansarif.libs:bottomnavbarlib:{latestVersion}'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

`//project level gradle

buildscript {

    repositories {
        google()
        jcenter()
        maven {
            url  "https://dl.bintray.com/subsub/maven"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url  "https://dl.bintray.com/subsub/maven"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
