### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by djohannot** [subsub/lottiebottomnavbar#3]
Hi,
I did a pull request with some important changes, are you interested in it or not?

- Migration to AndroidX 
- Rewrote in Kotlin
- Remove the viewpager from the library
- Move files from the library to the sample file (images, etc.)

**Comment by subsub** [comment]
Hi @djohannot thanks a lot. let me check it first

**Comment by subsub** [comment]
Hi @djohannot why did you remove viewpager and what is the substitute for it?

**Comment by djohannot** [comment]
The idea is to let the user implement the behavior of the bottom bar the way he wants. 

You have define this listener on the bottombar that is a good idea, and you can use only this to manage your fragment. Therefore i didn't see the need to add it into the library as it might be a constraint for some project to have to support this view pager and not their own.

If you look at the modified sample, if works perfectly with the fragment outside of the library, and it makes the library smaller. It also reduce the responsability of the library to do only what it is made for: provide a bottom bar behavior :)

**Comment by subsub** [comment]
Oh I see. Great idea. it's merged.
Thanks man! :)

**Comment by djohannot** [comment]
thanks to you for this lib!

**Comment by djohannot** [comment]
Let me know when you deploy a new version and I will use it instead of my local AAR
