### ISSUE TITLE
Error build project

### ISSUE THREAD

**Issue by Jparrgam** [subsub/lottiebottomnavbar#4]
hi @subsub, I have error in compilation project with this library

> Caused by: Error: 1 exception was raised by workers:
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/Users/jaimeparragamboa/.gradle/caches/transforms-2/files-2.1/906b975542996316167d06d8493cf593/res/values/values.xml:7:5-52:

this line specific error in console build 

![Screen Shot 2019-03-14 at 1 22 10 PM](https://user-images.githubusercontent.com/8985838/54381683-5b0c9e80-465c-11e9-8a57-79a910c71fa0.png)

**Comment by subsub** [comment]
@Jparrgam have you tried `clean`, `rebuild`, or `invalidate cache and restart`?

**Comment by Jparrgam** [comment]
> @Jparrgam have you tried `clean`, `rebuild`, or `invalidate cache and restart`?

@subsub yes, even so the error is presented

**Comment by subsub** [comment]
@Jparrgam can you provide your project and app `build.gradle` ?

**Comment by djohannot** [comment]
@Jparrgam Do you still have the issue? you tried with the last version of the code? seems to work fine on my side

**Comment by ryancmcmanus** [comment]
@Jparrgam I was able to fix it on my side by adding this to an ids.xml file in my values directory: 

`<resources>
    <item name="main_view_pager" type="id"/>
</resources>`

**Comment by jaikeerthick** [comment]
Same problem now.. Any fix found?
